### ISSUE TITLE
Generate Page Issue

### ISSUE THREAD

**Issue by pankajthakur950** [pagesource/component-generator#22]
Creating new Page using ‘npm run generate’ generate Page component with error.

Steps to reproduce:

1. Run command: 'npm/yarn run generate'
2. Select the app in which you want to generate
3. Enter the name of page(e.g. Details)
4. Page is created under pages directory in selected app and route entry in route page.
5. index.js file in Pages directory has two issues:

- while page generation, console shows linting error for missing semicolon.

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/5993534/158550084-f4af34fd-00a5-4314-a63a-487e78f37959.png)

- created page refers the file in path ‘../components/templates/DetailsName’ which is not created during generate command.

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/5993534/158550128-573b166c-5b8e-4ba5-98a3-15287791d9b8.png)

**Comment by khus29** [comment]
Issue fixed i version -   "version": "1.1.1",
