### ISSUE TITLE
New component in packages/UI folder

### ISSUE THREAD

**Issue by pankajthakur950** [pagesource/component-generator#24]
Not able to generate new component in packages/UI folder. Steps are mentioned in screenshot below:
 
<img width="870" alt="Screenshot 2022-03-21 at 11 08 29 AM" src="https://user-images.githubusercontent.com/5993534/159210150-962daf4a-a282-448a-b147-38884a1be7e8.png">

**Comment by khus29** [comment]
@pankajthakur950 , This is not an issue. It is expecting directory `/atoms` to create the desired component. However, there is an option to provide a custom path as well. Let's connect if you need any other details.

**Comment by khus29** [comment]
Implemented in version - "version": "1.2.0",
