### ISSUE TITLE
Type 'RenderResultstypeof ........... HTMLElement>' is not assignable to type 'string'.

### ISSUE THREAD

**Issue by siddharthasharma04** [pagesource/component-generator#28]
Steps:
- Generate MicroApp.
- Add/Generate new component 
`yarn generate`
- Below Error in test file

![image](https://user-images.githubusercontent.com/16999075/159252027-2bdaf89e-7624-4746-a9be-7e0c2a7d357f.png)

**Comment by khus29** [comment]
Fixed in version - "version": "1.2.0",
